export const CATEGORIES = ["All", "Vegetables & Tubers", "Meat & Poultry", "Seafood", "Grains & Flour", "Spices & Condiments", "Drinks"];

export const PRODUCTS = [
  // ─── Vegetables & Tubers ───
  {
    id: "yam-001",
    name: "Premium Puna Yam",
    category: "Vegetables & Tubers",
    price: 8.99,
    unit: "per tuber (3–4kg)",
    emoji: "🍠",
    badge: "Bestseller",
    badgeColor: "#e8b14a",
    description: "Fresh Nigerian Puna yam, perfect for pounded yam, yam porridge, fried yam, and asaro. Sourced directly from Benue State farms.",
    origin: "Benue State, Nigeria",
    inStock: true,
    rating: 4.9,
    reviews: 312,
  },
  {
    id: "yam-002",
    name: "Water Yam (Isu Ewura)",
    category: "Vegetables & Tubers",
    price: 6.49,
    unit: "per tuber (~2kg)",
    emoji: "🥔",
    badge: null,
    description: "Authentic water yam ideal for amala. Smooth texture with rich flavour. A staple of Yoruba cuisine.",
    origin: "Oyo State, Nigeria",
    inStock: true,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: "okro-001",
    name: "Fresh Okro (Okra)",
    category: "Vegetables & Tubers",
    price: 2.99,
    unit: "per 500g",
    emoji: "🫛",
    badge: "Fresh Today",
    badgeColor: "#4caf50",
    description: "Freshly imported okro pods — tender, vibrant green, perfect for okro soup with fufu or eba. Rich in fibre and vitamins.",
    origin: "Ghana / Nigeria",
    inStock: true,
    rating: 4.8,
    reviews: 254,
  },
  {
    id: "plantain-001",
    name: "Ripe Plantains",
    category: "Vegetables & Tubers",
    price: 1.99,
    unit: "per bunch (~6 fingers)",
    emoji: "🍌",
    badge: null,
    description: "Sweet ripe plantains for dodo (fried plantain). Deep golden yellow, ready to fry. A crowd favourite at any Nigerian party.",
    origin: "Caribbean / West Africa",
    inStock: true,
    rating: 4.9,
    reviews: 421,
  },
  {
    id: "cassava-001",
    name: "Fresh Cassava Root",
    category: "Vegetables & Tubers",
    price: 3.49,
    unit: "per kg",
    emoji: "🌾",
    badge: null,
    description: "Fresh cassava for making eba, fufu, or tapioca. High-quality tubers with low bitterness.",
    origin: "Nigeria",
    inStock: true,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: "cocoyam-001",
    name: "Cocoyam (Taro Root)",
    category: "Vegetables & Tubers",
    price: 4.29,
    unit: "per kg",
    emoji: "🫚",
    badge: null,
    description: "Fresh cocoyam for ofe onugbu (bitter leaf soup) or cocoyam fufu. Dense, starchy, and flavourful.",
    origin: "Nigeria",
    inStock: true,
    rating: 4.4,
    reviews: 67,
  },

  // ─── Meat & Poultry ───
  {
    id: "chicken-001",
    name: "Whole Broiler Chicken",
    category: "Meat & Poultry",
    price: 12.99,
    unit: "per bird (~1.8kg)",
    emoji: "🍗",
    badge: "Halal",
    badgeColor: "#2e7d32",
    description: "Free-range whole chicken, halal-certified. Perfect for Nigerian peppered chicken, jollof rice, or suya marinade.",
    origin: "UK Farm (Halal)",
    inStock: true,
    rating: 4.8,
    reviews: 503,
  },
  {
    id: "chicken-002",
    name: "Chicken Drumsticks",
    category: "Meat & Poultry",
    price: 5.99,
    unit: "per 1kg pack",
    emoji: "🍗",
    badge: "Halal",
    badgeColor: "#2e7d32",
    description: "Meaty drumsticks, ideal for marinating in suya spice or stewing in groundnut soup. Halal certified.",
    origin: "UK Farm (Halal)",
    inStock: true,
    rating: 4.7,
    reviews: 287,
  },
  {
    id: "beef-001",
    name: "Beef (Isan) — Chuck Cut",
    category: "Meat & Poultry",
    price: 10.99,
    unit: "per 1kg",
    emoji: "🥩",
    badge: "Halal",
    badgeColor: "#2e7d32",
    description: "Tender beef chuck, perfect for Nigerian beef stew, egusi soup with beef, or peppered beef. Slow-cooks to perfection.",
    origin: "UK Farm (Halal)",
    inStock: true,
    rating: 4.8,
    reviews: 367,
  },
  {
    id: "beef-002",
    name: "Cow Tripe (Shaki)",
    category: "Meat & Poultry",
    price: 7.49,
    unit: "per 500g",
    emoji: "🫀",
    badge: null,
    description: "Pre-cleaned cow tripe (shaki), essential for pepper soup or obe ata dindin. Rich, chewy, deeply flavoured.",
    origin: "UK Halal Butcher",
    inStock: true,
    rating: 4.6,
    reviews: 145,
  },
  {
    id: "goat-001",
    name: "Goat Meat (Asun Cut)",
    category: "Meat & Poultry",
    price: 14.99,
    unit: "per 1kg",
    emoji: "🐐",
    badge: "Fan Favourite",
    badgeColor: "#c62828",
    description: "Bone-in goat meat, the go-to for asun, goat pepper soup, and Nigerian wedding rice. Rich umami flavour.",
    origin: "UK Halal Butcher",
    inStock: true,
    rating: 4.9,
    reviews: 441,
  },

  // ─── Grains & Flour ───
  {
    id: "flour-001",
    name: "Semovita (Golden Penny)",
    category: "Grains & Flour",
    price: 4.99,
    unit: "2kg bag",
    emoji: "🌾",
    badge: null,
    description: "Smooth semolina wheat flour for making semo swallow. Pairs beautifully with egusi, okro, or banga soup.",
    origin: "Nigeria (Imported)",
    inStock: true,
    rating: 4.8,
    reviews: 322,
  },
  {
    id: "flour-002",
    name: "Eba / Garri (Yellow)",
    category: "Grains & Flour",
    price: 3.49,
    unit: "1.5kg bag",
    emoji: "🥣",
    badge: "Staple",
    badgeColor: "#f9a825",
    description: "Premium yellow garri from cassava. Use for eba, drink as a refreshing cold garri, or snack dry with groundnuts.",
    origin: "Nigeria (Imported)",
    inStock: true,
    rating: 4.9,
    reviews: 511,
  },
  {
    id: "flour-003",
    name: "Poundo Yam Flour",
    category: "Grains & Flour",
    price: 5.49,
    unit: "2kg bag",
    emoji: "🍠",
    badge: null,
    description: "Instant pounded yam flour — ready in minutes. Smooth, elastic texture, great for all swallow soups.",
    origin: "Nigeria (Imported)",
    inStock: true,
    rating: 4.7,
    reviews: 398,
  },

  // ─── Spices & Condiments ───
  {
    id: "spice-001",
    name: "Suya Spice Mix",
    category: "Spices & Condiments",
    price: 3.99,
    unit: "200g tin",
    emoji: "🌶️",
    badge: "Hot 🔥",
    badgeColor: "#b71c1c",
    description: "Authentic West African suya spice (yaji) with ground groundnuts, chilli, ginger, and garlic. Perfect dry rub for beef or chicken.",
    origin: "Nigeria",
    inStock: true,
    rating: 4.9,
    reviews: 617,
  },
  {
    id: "spice-002",
    name: "Cameroon Pepper (Nsukka)",
    category: "Spices & Condiments",
    price: 2.49,
    unit: "100g bag",
    emoji: "🫙",
    badge: null,
    description: "Dried Cameroon / Nsukka pepper — smoky, earthy heat that is the secret to authentic Nigerian soups and stews.",
    origin: "Nigeria / Cameroon",
    inStock: true,
    rating: 4.8,
    reviews: 234,
  },
  {
    id: "spice-003",
    name: "Egusi (Melon Seeds)",
    category: "Spices & Condiments",
    price: 5.99,
    unit: "500g bag",
    emoji: "🌻",
    badge: "Must-Have",
    badgeColor: "#ff7043",
    description: "Ground white melon seeds for egusi soup — the king of Nigerian soups. Rich in protein, nutty and deeply savoury.",
    origin: "Nigeria",
    inStock: true,
    rating: 4.9,
    reviews: 489,
  },
  {
    id: "spice-004",
    name: "Crayfish (Dried)",
    category: "Spices & Condiments",
    price: 4.29,
    unit: "200g bag",
    emoji: "🦐",
    badge: null,
    description: "Ground dried crayfish — the umami backbone of Nigerian cooking. Adds depth to egusi, banga, okro and pepper soup.",
    origin: "Nigeria",
    inStock: true,
    rating: 4.7,
    reviews: 312,
  },

  // ─── Drinks ───
  {
    id: "drink-001",
    name: "Malta Guinness (Pack of 6)",
    category: "Drinks",
    price: 6.99,
    unit: "6 × 330ml cans",
    emoji: "🥤",
    badge: null,
    description: "Non-alcoholic malt drink, beloved across West Africa and the Caribbean. Rich, sweet, and energising.",
    origin: "Nigeria (Imported)",
    inStock: true,
    rating: 4.8,
    reviews: 287,
  },
  {
    id: "drink-002",
    name: "Zobo Drink (Hibiscus)",
    category: "Drinks",
    price: 3.99,
    unit: "1 litre bottle",
    emoji: "🌺",
    badge: "Handcrafted",
    badgeColor: "#880e4f",
    description: "Traditional Nigerian zobo — hibiscus flower drink infused with ginger, pineapple, and cloves. Refreshing and antioxidant-rich.",
    origin: "UK Made (Nigerian Recipe)",
    inStock: true,
    rating: 4.9,
    reviews: 198,
  },
];
